In [2]:
import pandas as pd
import numpy as np

    Selecting

Se refiere a seleccionar columnas o filas en un DataFrame usando índices, etiqeutas o condiciones.

In [3]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "City": ["NY", "Paris", "London", "Berlin"]
})

#Seleccionar filas por índice (iloc -> por posición)
print(df.iloc[0:2])
print()

#Seleccionar filas por etiqueta (loc -> por nombre de índice)
print(df.loc[0:2, ["Name"]])

    Name  Age   City
0  Alice   25     NY
1    Bob   30  Paris

      Name
0    Alice
1      Bob
2  Charlie

In [4]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Emilio"],
    "Age":  [25, None, 35, 40, 28],
    "City": ["NY", "Paris", None, "Berlin", "London"]
})

#.isnull() Devuelve True si el valor es nulo (NaN o None).
print(df1[df1["Age"].isnull()]) #Filas donde Age está vacío
print()

#.notnull() Devuelve True si el valor no es nulo.
print(df1[df1["City"].notnull()]) #Devuelve True si el valor no es nulo
print()

#.any() Verifica si al menos un valor es True en un eje.
print(df1.isnull().any()) #Ver si hay algún nulo por columna.
print()

#.all() Verifica si todos los valores son True en un eje.
print(df1.isnull().all()) #Verifica que columnas tienen todos los valores nulos.

  Name  Age   City
1  Bob  NaN  Paris

     Name   Age    City
0   Alice  25.0      NY
1     Bob   NaN   Paris
3   David  40.0  Berlin
4  Emilio  28.0  London

Name    False
Age      True
City     True
dtype: bool

Name    False
Age     False
City    False
dtype: bool

    Indexing with isin

Se usa para filtrar filas basandose en si los valores de una columna están dentro de una lista de opciones.

In [5]:
#Selecionar filas donde City es "London" o "Paris"
filtered = df[df["City"].isin(["London", "Paris"])]
filtered

      Name  Age    City
1      Bob   30   Paris
2  Charlie   35  London

    Where

Permite aplicar una condición, por ejemplo:

Los valores que cumplen se mantienen, los que no se reemplazan por NaN (a menos que especifiques otro valor con other=).

In [6]:
print(df.where(df["Age"] > 30, other=0))

      Name  Age    City
0        0    0       0
1        0    0       0
2  Charlie   35  London
3    David   40  Berlin

    Query

Permite filtrar datos escribiendo condiciones como una expresión de SQL dentro de un string.
Es más legible y conviene para consultas complejas.

In [7]:
#Filtrar filas donde Age > 25 y City = 'Paris'
print(df.query("Age > 25 and City == 'Paris'"))

  Name  Age   City
1  Bob   30  Paris

    Setting and Resetting Index

El índice en pandas no siempre tiene que ser 0,1,2,etc.

Puedes configurar cualquier columna como índice y luego resetearlo cuando lo necesites.

In [8]:
#Establecer "Name" como índice
dfx = df.set_index("Name")
print(dfx)

print()

#Resetear el índice (volver al indice numerico por defecto)
dfg = dfx.reset_index()
print(dfg)

         Age    City
Name
Alice     25      NY
Bob       30   Paris
Charlie   35  London
David     40  Berlin

      Name  Age    City
0    Alice   25      NY
1      Bob   30   Paris
2  Charlie   35  London
3    David   40  Berlin

    Reindexing 

reindex() sirve para cambiar el indice de un DataFrame o Serie

-Puedes agregar/quitar indices

-Los valores que no existan se llenan con NaN.

In [9]:
print("Original:\n", df)

# Reindex con índices nuevos
new_index = [1, 2, 3, 4, 5]
df2 = df.reindex(new_index)
print("\nReindexed:\n", df2)

Original:
       Name  Age    City
0    Alice   25      NY
1      Bob   30   Paris
2  Charlie   35  London
3    David   40  Berlin

Reindexed:
       Name   Age    City
1      Bob  30.0   Paris
2  Charlie  35.0  London
3    David  40.0  Berlin
4      NaN   NaN     NaN
5      NaN   NaN     NaN

    Forward Filling
ffill() Llena valores faltantes (NaN) con el último valor válido conocido.

In [10]:
df2_ffill = df2.ffill()
df2_ffill

      Name   Age    City
1      Bob  30.0   Paris
2  Charlie  35.0  London
3    David  40.0  Berlin
4    David  40.0  Berlin
5    David  40.0  Berlin

    Backward Filling
bfill() Llena valores faltantes con el proximo valor válido conocido.

In [11]:
df2_bfill = df2.bfill()
df2_bfill

      Name   Age    City
1      Bob  30.0   Paris
2  Charlie  35.0  London
3    David  40.0  Berlin
4      NaN   NaN     NaN
5      NaN   NaN     NaN

    MultiIndexing
Permite tener multiples niveles de índices en filas o columnas.

In [13]:
arrays = [
    ['USA', 'USA', 'Canada', 'Canada'],
    ['NY', 'California', 'Toronto', 'Montereal']
]

#Ejemplo MultiIndex en filas
index = pd.MultiIndex.from_arrays(arrays, names=("Country", "City"))
df3 = pd.DataFrame({"Population": [0.5, 39.5, 2.9, 1.7]}, index=index)
print(df3)

                    Population
Country City
USA     NY                 0.5
        California        39.5
Canada  Toronto            2.9
        Montereal          1.7

In [14]:
df4 = pd.DataFrame({
        ("Sales", "2022"): [100, 200],
        ("Sales", "2023"): [150, 250],
        ("Profit", "2022"): [30, 50],
        ("Profit", "2023"): [40, 60],
    },
    index=["Product A", "Product B"]
)

print(df4)

          Sales      Profit
           2022 2023   2022 2023
Product A   100  150     30   40
Product B   200  250     50   60